/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption
{
    /**
     * check if GN_FEATURE_USE_DEFUALT is turned on or not
     */
    public static final boolean GN_FEATURE_USE_DEFUALT = false;
}
